apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-player-frontend
  labels:
    app: music-player-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: music-player-frontend
  template:
    metadata:
      labels:
        app: music-player-frontend
    spec:
      containers:
        - name: frontend
          image: music-player-frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8040
---
apiVersion: v1
kind: Service
metadata:
  name: music-player-frontend-service
spec:
  type: NodePort
  selector:
    app: music-player-frontend
  ports:
    - protocol: TCP
      port: 8040
      targetPort: 8040
      nodePort: 30040  # Optional: fixed port